#!/bin/bash

echo "🔧 Setting environment variables for Firebase App Hosting..."
echo ""
echo "⚠️  You need to set these environment variables in the Firebase Console:"
echo ""
echo "Go to: https://console.firebase.google.com/project/smarttasker-gk/apphosting/backends/asia-southeast1/st-backend"
echo ""
echo "Click on 'Environment variables' and add the following:"
echo ""
echo "PUBLIC Environment Variables:"
echo "----------------------------"
echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY"
echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN"
echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID"
echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET"
echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID"
echo "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID"
echo "NEXT_PUBLIC_VAPID_KEY=$NEXT_PUBLIC_VAPID_KEY"
echo ""
echo "SECRET Environment Variables (add as secrets):"
echo "----------------------------------------------"
echo "GEMINI_API_KEY=(your key)"
echo "VAPID_PRIVATE_KEY=(your key)"
echo "VAPID_SUBJECT=(your subject)"
echo "SERVICE_ACCOUNT_KEY=(your service account JSON)"
echo "GOOGLE_CLIENT_ID=(your client ID)"
echo "GOOGLE_CLIENT_SECRET=(your client secret)"
echo "GOOGLE_REDIRECT_URI=(update to your production URL)"
echo ""
